accountscommandside:
  image: java:8
  working_dir: /app
  volumes:
    - ./accounts-command-side-service/build/libs:/app
  command: java -jar /app/accounts-command-side-service.jar 
  ports:
    - "8080:8080"
  environment:
    EVENT_STORE_USER_ID:
    EVENT_STORE_PASSWORD:
    EVENT_STORE_URL:
    EVENT_STORE_STOMP_SERVER_HOST:
    EVENT_STORE_STOMP_SERVER_PORT:

transactionscommandside:
  image: java:8
  working_dir: /app
  volumes:
    - ./transactions-command-side-service/build/libs:/app
  command: java -jar /app/transactions-command-side-service.jar 
  ports:
    - "8082:8080"
  environment:
    EVENT_STORE_USER_ID:
    EVENT_STORE_PASSWORD:
    EVENT_STORE_URL:
    EVENT_STORE_STOMP_SERVER_HOST:
    EVENT_STORE_STOMP_SERVER_PORT:


accountsqueryside:
  image: java:8
  working_dir: /app
  volumes:
    - ./accounts-query-side-service/build/libs:/app
  command: java -jar /app/accounts-query-side-service.jar --spring.data.mongodb_uri=mongodb://database/CQRS
  ports:
    - "8081:8080"
  links:
    - mongodb
  environment:
    EVENT_STORE_USER_ID:
    EVENT_STORE_PASSWORD:
    EVENT_STORE_URL:
    EVENT_STORE_STOMP_SERVER_HOST:
    EVENT_STORE_STOMP_SERVER_PORT:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb

mongodb:
  image: mongo:latest
  hostname: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"

