apigateway:
  image: java:openjdk-8u91-jdk
  command: java -jar /app/api-gateway-service.jar --accounts.commandside.service.host=accountscommandside --transfers.commandside.service.host=transactionscommandside --accounts.queryside.service.host=accountsqueryside --customers.commandside.service.host=customerscommandside  --customers.queryside.service.host=customersqueryside
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb
  ports:
    - "8080:8080"

accountscommandside:
  image: java:openjdk-8u91-jdk
  command: java -jar /app/accounts-command-side-service.jar
  ports:
    - "8085:8080"

transactionscommandside:
  image: java:openjdk-8u91-jdk
  command: java -jar /app/transactions-command-side-service.jar
  ports:
    - "8082:8080"

accountsqueryside:
  image: java:openjdk-8u91-jdk
  command: java -jar /app/accounts-query-side-service.jar
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb
  ports:
    - "8081:8080"

customerscommandside:
  image: java:openjdk-8u91-jdk
  command: java -jar /app/customers-command-side-service.jar
  ports:
    - "8083:8080"

customersqueryside:
  image: java:openjdk-8u91-jdk
  command: java -jar /app/customers-query-side-service.jar
  ports:
    - "8084:8080"
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb

mongodb:
  image: mongo:3.0.4
  hostname: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"
