apigateway:
  extends:
    file: docker-compose-common.yml
    service: apigateway
  volumes:
    - ./api-gateway-service/build/libs:/app
  links:
    - accountscommandside
    - transactionscommandside
    - accountsqueryside
    - customerscommandside
    - customersqueryside
    - mongodb

accountscommandside:
  extends:
    file: docker-compose-common.yml
    service: accountscommandside
  volumes:
    - ./accounts-command-side-service/build/libs:/app
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

transactionscommandside:
  extends:
    file: docker-compose-common.yml
    service: transactionscommandside
  volumes:
    - ./transactions-command-side-service/build/libs:/app
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}


accountsqueryside:
  extends:
    file: docker-compose-common.yml
    service: accountsqueryside
  volumes:
    - ./accounts-query-side-service/build/libs:/app
  links:
    - mongodb
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

customerscommandside:
  extends:
    file: docker-compose-common.yml
    service: customerscommandside
  volumes:
    - ./customers-command-side-service/build/libs:/app
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

customersqueryside:
  extends:
    file: docker-compose-common.yml
    service: customersqueryside
  image: java:openjdk-8u91-jdk
  volumes:
    - ./customers-query-side-service/build/libs:/app
  links:
    - mongodb
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

mongodb:
  extends:
    file: docker-compose-common.yml
    service: mongodb
