apigateway:
  build: ./api-gateway-service/
  ports:
    - "8080:8080"
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb
    ACCOUNTS_COMMANDSIDE_SERVICE_HOST: accountscommandside
    TRANSFERS_COMMANDSIDE_SERVICE_HOST: transactionscommandside
    ACCOUNTS_QUERYSIDE_SERVICE_HOST: accountsqueryside
    CUSTOMERS_COMMANDSIDE_SERVICE_HOST: customerscommandside
    CUSTOMERS_QUERYSIDE_SERVICE_HOST: customersqueryside


accountscommandside:
  build: ./accounts-command-side-service/
  ports:
    - "8085:8080"

transactionscommandside:
  build: ./transactions-command-side-service/
  ports:
    - "8082:8080"

accountsqueryside:
  build: ./accounts-query-side-service/
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb
  ports:
    - "8081:8080"

customerscommandside:
  build: ./customers-command-side-service/
  ports:
    - "8083:8080"

customersqueryside:
  build: ./customers-query-side-service/
  ports:
    - "8084:8080"
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb

mongodb:
  image: mongo:3.0.4
  hostname: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"
