apigateway:
  extends:
    file: docker-compose-common.yml
    service: apigateway
  links:
    - accountscommandside
    - transactionscommandside
    - accountsqueryside
    - customerscommandside
    - customersqueryside
    - mongodb

accountscommandside:
  extends:
    file: docker-compose-common.yml
    service: accountscommandside
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

transactionscommandside:
  extends:
    file: docker-compose-common.yml
    service: transactionscommandside
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}


accountsqueryside:
  extends:
    file: docker-compose-common.yml
    service: accountsqueryside
  links:
    - mongodb
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb

customerscommandside:
  extends:
    file: docker-compose-common.yml
    service: customerscommandside
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

customersqueryside:
  extends:
    file: docker-compose-common.yml
    service: customersqueryside
  links:
    - mongodb
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb

mongodb:
  extends:
    file: docker-compose-common.yml
    service: mongodb
